# Generated by Django 3.1 on 2020-08-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algs_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmset',
            name='name',
            field=models.CharField(default='nul', max_length=100),
            preserve_default=False,
        ),
    ]
