# Generated by Django 3.1 on 2020-08-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algs_site', '0002_algorithmset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='image',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithmset',
            name='image',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='image',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
