# Generated by Django 3.1 on 2020-08-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algs_site', '0003_auto_20200819_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(upload_to='images/algorithm'),
        ),
        migrations.AlterField(
            model_name='algorithmset',
            name='image',
            field=models.ImageField(upload_to='images/algorithm_set'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='image',
            field=models.ImageField(upload_to='images/puzzle/'),
        ),
    ]
