# Generated by Django 3.1 on 2020-08-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algs_site', '0004_auto_20200819_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='alt_text',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithmset',
            name='alt_text',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='alt_text',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
