# Generated by Django 3.1 on 2020-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algs_site', '0005_auto_20200819_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='comments',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithmset',
            name='comments',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='comments',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
