# Generated by Django 3.1 on 2020-08-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algs_site', '0007_auto_20200825_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algs_site.case'),
        ),
    ]
