# Generated by Django 3.1 on 2020-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algs_site', '0008_auto_20200825_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='alt_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(null=True, upload_to='images/algorithm'),
        ),
        migrations.AlterField(
            model_name='algorithmset',
            name='alt_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='algorithmset',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='algorithmset',
            name='image',
            field=models.ImageField(null=True, upload_to='images/algorithm_set'),
        ),
        migrations.AlterField(
            model_name='case',
            name='alt_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(null=True, upload_to='images/case'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='alt_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='image',
            field=models.ImageField(null=True, upload_to='images/puzzle/'),
        ),
    ]
