# Generated by Django 3.1 on 2020-08-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algs_site', '0009_auto_20200825_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/algorithm'),
        ),
        migrations.AlterField(
            model_name='algorithmset',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='algorithmset',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='algorithmset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/algorithm_set'),
        ),
        migrations.AlterField(
            model_name='case',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/case'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/puzzle/'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='algorithm',
            unique_together={('name', 'case')},
        ),
        migrations.AlterUniqueTogether(
            name='algorithmset',
            unique_together={('name', 'puzzle')},
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('name', 'puzzle')},
        ),
    ]
