# Generated by Django 3.1 on 2020-08-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algs_site', '0010_auto_20200825_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='algorithm_sets',
            field=models.ManyToManyField(to='algs_site.AlgorithmSet'),
        ),
    ]
